project:
  type: book

book:
  title: "intro_R"
  author:
    - "Agustin Alesso"
    - "Patricia Acetta"
#  date: "9/26/2023"
  chapters:
    - index.qmd
    - 01_introduccion.qmd
    - 02_basics.qmd
    - 03_paquetes.qmd
    - 04_import.qmd
    - 05_wrangling.qmd
    - 06_viz.qmd
    - 07_reports.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



