project:
  type: book

book:
  title: "Introducción al Análisis de Datos con R"
  author:
    - "Agustin Alesso"
    - "Patricia Acetta"
#  date: "9/26/2023"
  chapters:
    - index.qmd
    - 00_introduction.qmd
    - 01_install.qmd
    - 02_cloud.qmd
    - 03_basics.qmd
    - 04_paquetes.qmd
    - 05_import.qmd
    - 06_wrangling.qmd
    - 07_viz.qmd
    # - 08_reports.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt

lang: es

execute:
  error: true
